### ISSUE TITLE
Ao tentar extrair recebo o seguinte erro

### ISSUE THREAD

**Issue by chapzin** [Niddhogur/nfe-extractor#1]
![image](https://user-images.githubusercontent.com/930047/36402353-a4c8031a-15bc-11e8-87f8-cd7a28e0f050.png)

**Comment by Niddhogur** [comment]
Oi!

Eu migrei para a linguagem C# (e acabei esquecendo de desativar esse repositório), acredito que este esteja bastante defasado. O novo projeto já possui uma release (ainda necessita algumas melhorias), e pode ser encontrado em [nfeXtrator](https://github.com/Niddhogur/nfeXtractor/releases).

**Comment by chapzin** [comment]
Gostaria de um contato seu, pois tenho uma proposta de trabalho para você caso esteja interessado.

**Comment by Niddhogur** [comment]
Enviei um e-mail pro endereço indicado no seu perfil! Obrigado!
